### PR TITLE
Branding

### PR DESCRIPTION
**Pull request by ndiesslin**
Added favicon and switched links back to blue.

### CODE REVIEW

**Comment by adamvoss** [comment]
Awesome!  Thanks!

Any chance you have a copy of the favicon.ico with a transparent background?  This one has a white background while the main macchina website is transparent.

**Comment by ndiesslin** [comment]
@adamvoss good catch, I just added the transparent favicon. Thank you!

**Comment by adamvoss** [comment]
Hmm, something is up with that.  It does not render nearly as cleanly as macchina.cc:

image

Looking at the .ico in my file browser I don't see the same green though...

**Comment by ndiesslin** [comment]
Oh that's odd, I'll try exporting it again and see if it changes how it renders. I wasn't seeing this on my end, but it might be something with the file.

**Comment by adamvoss** [comment]
Since there was an vector version of the logo from the first branding PR, I used that with https://realfavicongenerator.net (which I have used successfully on other projects) to generate a new favicon.ico.

Thanks for this!

**Comment by ndiesslin** [comment]
That works for me. Thanks for making the adjustment on this @adamvoss!

**Pull request merged**
